[package]
name = "enumeration"
version = "0.2.0"
description = "Add-only set of keys with numbering and two-way lookup"
repository = "https://github.com/research-ag/enumeration"
keywords = [ "bijective", "map", "list" ]
license = "Apache-2.0"

[dependencies]
core = "2.5.0"

[requirements]
moc = "1.0.0"

[toolchain]
moc = "1.8.2"
