name: App build
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

env:
  mops_version: 0.13.0
  moc_version: 0.9.1
  dfx_version: 0.14.1

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make bin directory
        run: mkdir -p /home/runner/bin

      - name: "install Motoko binaries"
        run: |
          wget https://github.com/dfinity/motoko/releases/download/${{ env.moc_version }}/motoko-linux64-${{ env.moc_version }}.tar.gz
          tar -xzf motoko-linux64-${{ env.moc_version }}.tar.gz -C /home/runner/bin
          echo "/home/runner/bin" >> $GITHUB_PATH

      - name: "install mops"
        run: |          
          npm i -g ic-mops@${{ env.mops_version }}

      - name: Get dfx
        run: |
          DFX_VERSION=${{ env.dfx_version }} sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"

      - name: install mops packages
        run: mops install

      - name: "test"
        run: DFX_MOC_PATH=/home/runner/bin/moc mops test
