name: App build
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

env:
  mops_version: latest

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Install mops
        uses: ZenVoich/setup-mops@v1.2.0

      - name: Make sure moc is installed
        run: mops toolchain bin moc || mops toolchain use moc latest
  
      - name: Run mops test
        run: mops test

